language: cpp

matrix:
    include:
        - os: osx
            env: CXX=g++-5
        - os: osx
            env: CXX=clang++

        - os: linux
            env: CXX=g++-5
            addons:
                apt:
                    packages:
                        - g++-5
                        - gcc-5
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-precise
                        - llvm-toolchain-precise-3.8
        - os: linux
            env: CXX=clang++-3.8
            addons:
                apt:
                    packages:
                        - clang-3.8
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-precise
                        - llvm-toolchain-precise-3.8

script:
    - uname -a
    - make -v 
    - ls 
    - ls ./include
    - ls ./src
    - ls ./src/obj
    - make CXXFLAGS="${CXXFLAGS}" CXX="${CXX}" install
    - make CXXFLAGS="${CXXFLAGS}" CXX="${CXX}" test1
    - make CXXFLAGS="${CXXFLAGS}" CXX="${CXX}" test2
    - make CXXFLAGS="${CXXFLAGS}" CXX="${CXX}" test3
